# -*- coding: utf-8 -*-
"""numpy_basics_simpli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cHpMC7KvWs5RM74TsisXZSIlAXxQrGCn
"""

import numpy as np

arr1 = np.array([[10, 20, 30], [20, 30, 40]])
arr2 = np.array([30, 20, 10])

np.add(arr1, arr2)

np.subtract(arr1, arr2)

np.multiply(arr1, arr2)

np.divide(arr1, arr2)

'''
a1x+b1y+c1= 0
a2x + b2y + c2 = 0
a3x+b3y+c3 = 0

ax +by = -c*1

[[a1, b1, c1]
[a2, b2, c2]]


# features...

fare1 = (distance * imp_dista) + (time * imp_time) + (veh_type * imp) + ....
x1, x2, x3, .... y1


(3*imp_d) + (1 * imp_time) + (2 * imp_veh) = 75

[[3, 1, 2, 75]
[5, 1, 3, 150]
[4, 0, 1, 30]
[2, 1, 1, 20]]

'''

np.mean([300, 500, 400, 200, 2000])



np.mean([10, 12, 15, 75, 40, 65, 84, 90, 95, 100, 100])



a_section_avg = np.mean([10, 20, 80, 90, 100, 0])

b_section_avg = np.mean([48, 52, 49, 51, 47, 53])

b_section_avg

np.std([10, 20, 80, 90, 100, 0], axis=0)

np.std([48, 52, 49, 51, 47, 53])

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([50, 60, 70, 80])

np.median(arr1)

arr3 = np.array([10, 20, 32, 47, 63, 97, 99, 14, 76, 99, 100, 65, 17, 72, 78, 67, 84, 89])

np.percentile(arr3, 25)

len(arr3)

rank = (25/100)*(19)



rank

arr4 = np.sort(arr3)

arr4

0.5*(19)

'''
1+(N-1)*p
'''

1+(17)*0.25

32+(0.25*(47-32))

67+(0.5*(72-67))

'''
numpy way...
rank = 1+ (17*0.25)
32 + (0.25 *(47-32)) = 35.75

excel way...
rank = 0.25*(19)
20 + (0.75)*(32-20) = 29.0

'''



x = np.array(['Hello','World'])
y = np.array(['Welcome', 'Learners'])
result = np.char.add(x,y)
print(result)

x

np.char.replace(x, 'Hello', 'Hi')

np.char.upper(x)

np.char.lower(x)



arr1 = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7]])

arr1[1, 1]

arr1[1]

arr1[-1]

arr1[:, 1]

arr1[0]



temp_array = np.random.randint(1, 100, size=(5, 5, 3))

temp_array

temp_array[0]

arr1 = temp_array[0]

arr2 = temp_array[1]

np.add(arr1, arr2)

temp_array[0, 0]

temp_array[0, 1, 0]

temp_array[1]

temp_array[1, 1]

temp_array[1, 1, 1]

x = np.array([[1, 2], [2, 3], [3, 4]])

x.shape

temp_array

temp_array[0, 0, -1]

import numpy as np
Employee_rating = np.array([1, 4, 3, 5, 6, 8, 9, 10, 12])
print(Employee_rating[1:7])

Books = np.array(['Physics','DataScience','Maths','Python','Hadoop', 'OPPs', 'Java', 'Cloud'])
print(Books[5:])

X = np.array([8, 7, 6, 5, 4, 3, 2, 1])
print(X[1:6:3])

temp_array[:, 2:3, :]

temp_arr = np.random.randint(1, 100, (4, 4))

temp_arr

temp_arr[:3:2, :3:2]

temp_arr[:3:2, :3:2]

np.transpose(temp_arr)

inv_arr = np.linalg.inv(temp_arr)

np.matmul(temp_arr, inv_arr)

[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]

import pandas as pd

!pip install pandas

!pip install openpyxl

df = pd.read_excel('excl_data.xlsx')

type(df)

type(df['Dist'])

type(df['Dist'])

df[['Dist', 'time']]

df['Dist']/10

df.to_excel("my_excel.xlsx")

